# Generated by Django 2.1.4 on 2018-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181219_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/storage/emulated/0/django_projects/rentals/room_rentals/media/profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
