# Generated by Django 2.1.4 on 2018-12-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181219_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/storage/emulated/0/django_projects/rentals/room_rentals/media/profiles/default.png', upload_to='profiles/'),
        ),
    ]
