# Generated by Django 2.1.4 on 2018-12-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('furniture', models.TextField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('likes', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.FileField(upload_to='rooms/')),
                ('view_1', models.FileField(blank=True, null=True, upload_to='rooms/')),
                ('view_2', models.FileField(blank=True, null=True, upload_to='rooms/')),
                ('view_3', models.FileField(blank=True, null=True, upload_to='rooms/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
