# Generated by Django 2.1.4 on 2018-12-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
