# Generated by Django 2.1.4 on 2018-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20181220_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='likes',
            field=models.FloatField(default=0),
        ),
    ]
