# Generated by Django 2.1.4 on 2018-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='town',
            field=models.CharField(default='harare', max_length=255),
            preserve_default=False,
        ),
    ]
