# Generated by Django 2.1.4 on 2018-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_1',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_3',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
