# Generated by Django 2.1.4 on 2018-12-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view_3',
        ),
    ]
